import { alpha, makeStyles } from "@/theme";

/** Shared kit styles — every TruePas component renders from this one sheet. */
export const useStyles = makeStyles((t) => ({
  grid: { flexDirection: "row", flexWrap: "wrap", gap: t.spacing[5], alignItems: "flex-start" },

  card: {
    width: 300,
    padding: t.spacing[5],
    borderRadius: t.radii.xl,
    backgroundColor: t.colors.surface,
    borderWidth: t.sizes.fieldBorderWidth,
    borderColor: alpha(t.colors.surface, 0.8),
    gap: t.spacing[3],
    ...t.shadows.md,
  },
  wideCard: { width: 380 },
  statCard: { width: 176, gap: t.spacing[2] },
  clusterCard: {
    width: 300,
    flexDirection: "row",
    justifyContent: "center",
    gap: t.spacing[4],
  },
  segmentedCard: { flexDirection: "row", gap: t.spacing[1], padding: t.spacing[2], width: 300 },
  stepperCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", width: 300 },
  selectCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", width: 300, paddingVertical: t.spacing[4] },
  arrowCard: { flexDirection: "row", gap: t.spacing[3], width: 300, alignItems: "center" },
  arrowGhost: { flex: 1, height: 44, borderRadius: t.radii.lg, backgroundColor: t.colors.surfaceSunken, opacity: 0.5 },
  tabsCard: { flexDirection: "row", gap: t.spacing[5], width: 300 },
  calendarCard: { width: 380, gap: t.spacing[4] },
  ratingCard: { width: 380, flexDirection: "row", alignItems: "center", gap: t.spacing[3] },
  noteCard: { width: 300, backgroundColor: t.colors.surfaceSunken },

  /* text */
  body: { fontSize: t.fontSize.base, color: t.colors.textPrimary },
  cardTitle: { fontSize: t.fontSize.base, fontWeight: t.fontWeight.semibold, color: t.colors.textPrimary },
  helper: { fontSize: t.fontSize.xs, color: t.colors.textSecondary },
  paragraph: { fontSize: t.fontSize.sm, lineHeight: t.fontSize.sm * t.lineHeight.relaxed, color: t.colors.textSecondary },
  bigNumber: { fontSize: t.fontSize.xl, fontWeight: t.fontWeight.bold, color: t.colors.textPrimary },
  metric: { fontSize: t.fontSize["2xl"], fontWeight: t.fontWeight.bold, color: t.colors.textPrimary, letterSpacing: t.letterSpacing.tight },

  /* layout helpers */
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: t.spacing[3] },
  rowBaseline: { flexDirection: "row", alignItems: "baseline", gap: t.spacing[1] },
  grow: { flex: 1, gap: 2 },
  bulletRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[2] },
  bullet: { width: 6, height: 6, borderRadius: t.radii.full, backgroundColor: t.colors.actionPrimary },
  dividedRow: { paddingVertical: t.spacing[3], borderTopWidth: t.sizes.fieldBorderWidth, borderTopColor: t.colors.borderSubtle },
  dividedRowFirst: { borderTopColor: "transparent", paddingTop: t.spacing[1] },

  /* buttons */
  circle: {
    width: 48,
    height: 48,
    borderRadius: t.radii.full,
    backgroundColor: t.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    ...t.shadows.sm,
  },
  circleSolid: { backgroundColor: t.colors.actionPrimary },
  square: {
    width: 48,
    height: 48,
    borderRadius: t.radii.lg,
    backgroundColor: t.colors.surface,
    alignItems: "center",
    justifyContent: "center",
    ...t.shadows.sm,
  },
  squareSolid: { backgroundColor: t.colors.actionPrimary },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: t.spacing[2],
    paddingHorizontal: t.spacing[5],
    paddingVertical: t.spacing[2],
    borderRadius: t.radii.full,
    backgroundColor: t.colors.surface,
    ...t.shadows.sm,
  },
  pillSolid: { backgroundColor: t.colors.actionPrimary },
  pillLabel: { fontSize: t.fontSize.sm, fontWeight: t.fontWeight.semibold, color: t.colors.textPrimary, letterSpacing: t.letterSpacing.wide },
  pillLabelSolid: { color: t.colors.onActionPrimary },
  pillRow: { flexDirection: "row", gap: t.spacing[3], flexWrap: "wrap" },
  pressed: { opacity: t.opacity.pressed, transform: [{ scale: 0.97 }] },
  navPair: { flexDirection: "row", gap: t.spacing[2] },

  /* chart */
  bars: { flexDirection: "row", alignItems: "flex-end", gap: 8, height: 140 },
  bar: { flex: 1, borderRadius: t.radii.sm, backgroundColor: t.colors.actionPrimarySubtle },
  barAccent: { backgroundColor: t.colors.actionPrimary },

  /* segmented */
  segment: { flex: 1, alignItems: "center", paddingVertical: t.spacing[2], borderRadius: t.radii.md },
  segmentActive: { backgroundColor: t.colors.actionPrimary, ...t.shadows.sm },
  segmentLabel: { fontSize: t.fontSize.xs, fontWeight: t.fontWeight.medium, color: t.colors.textSecondary },
  segmentLabelActive: { color: t.colors.onActionPrimary },

  /* price rows */
  priceRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[3] },
  priceBadge: {
    width: 44,
    height: 44,
    borderRadius: t.radii.md,
    backgroundColor: t.colors.actionPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  priceText: { color: t.colors.onActionPrimary, fontWeight: t.fontWeight.bold, fontSize: t.fontSize.base },

  /* tabs */
  tabItem: { alignItems: "center", gap: t.spacing[2] },
  tabLabel: { fontSize: t.fontSize.base, color: t.colors.textSecondary },
  tabLabelActive: { color: t.colors.textPrimary, fontWeight: t.fontWeight.semibold },
  tabDot: { width: 6, height: 6, borderRadius: t.radii.full, backgroundColor: t.colors.actionPrimary },

  /* legend */
  legendRow: { flexDirection: "row", gap: t.spacing[4] },
  legendItem: { flexDirection: "row", alignItems: "center", gap: t.spacing[1.5] },
  legendDot: { width: 12, height: 12, borderRadius: t.radii.full },
  legendDotOutline: { backgroundColor: "transparent", borderWidth: 2, borderColor: t.colors.actionPrimary },
  legendDotSoft: { backgroundColor: t.colors.accentSubtle },

  /* slider */
  sliderTrack: {
    height: 10,
    borderRadius: t.radii.full,
    backgroundColor: t.colors.surfaceSunken,
    justifyContent: "center",
  },
  sliderFill: { position: "absolute", left: 0, width: "62%", height: 10, borderRadius: t.radii.full, backgroundColor: t.colors.actionPrimary },
  sliderKnob: {
    position: "absolute",
    left: "58%",
    width: 22,
    height: 22,
    borderRadius: t.radii.full,
    backgroundColor: t.colors.surface,
    ...t.shadows.sm,
  },

  /* rating */
  pinRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[1], marginTop: 2 },

  /* calendar */
  weekRow: { flexDirection: "row", justifyContent: "space-between" },
  weekLabel: { flex: 1, textAlign: "center", fontSize: 10, letterSpacing: t.letterSpacing.caps, color: t.colors.textMuted },
  daysGrid: { flexDirection: "row", flexWrap: "wrap" },
  dayCell: { width: `${100 / 7}%`, aspectRatio: 1, alignItems: "center", justifyContent: "center", borderRadius: t.radii.sm },
  dayInRange: { backgroundColor: t.colors.actionPrimarySubtle },
  daySelected: { backgroundColor: t.colors.actionPrimary, borderRadius: t.radii.sm },
  dayText: { fontSize: t.fontSize.sm, color: t.colors.textSecondary },
  dayTextSelected: { color: t.colors.onActionPrimary, fontWeight: t.fontWeight.semibold },
  pickCell: {
    width: `${100 / 3}%`,
    paddingVertical: t.spacing[3],
    alignItems: "center",
    borderRadius: t.radii.md,
  },
  pickCellActive: { backgroundColor: t.colors.actionPrimary },
  headerSlot: { width: 24, alignItems: "flex-start" },
  headerLabel: { flexDirection: "row", alignItems: "center", gap: t.spacing[1] },
  selectedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: t.spacing[2],
    paddingTop: t.spacing[3],
    borderTopWidth: t.sizes.fieldBorderWidth,
    borderTopColor: t.colors.borderSubtle,
  },

  /* TruePas product components */
  productCard: { width: "100%", gap: t.spacing[3] },
  productIcon: {
    width: 44,
    height: 44,
    borderRadius: t.radii.full,
    alignItems: "center",
    justifyContent: "center",
  },
  divider: { height: t.sizes.fieldBorderWidth, backgroundColor: t.colors.borderSubtle },
  mono: { fontFamily: t.fontFamily.mono.medium, fontSize: t.fontSize.sm, color: t.colors.textSecondary },
  strong: { fontWeight: t.fontWeight.semibold, color: t.colors.textPrimary },
  rowCenter: { flexDirection: "row", alignItems: "center", gap: t.spacing[2] },
  rowWrap: { flexDirection: "row", flexWrap: "wrap", gap: t.spacing[2] },
  historyRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[3], paddingVertical: t.spacing[1] },
  stepRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[3], minHeight: 28 },
  stepActive: { width: 16, height: 16, borderRadius: t.radii.full, backgroundColor: t.colors.actionPrimary },
  unreadDot: { width: 8, height: 8, borderRadius: t.radii.full, backgroundColor: t.colors.actionPrimary },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: t.radii.full,
    backgroundColor: t.colors.actionPrimary,
    alignItems: "center",
    justifyContent: "center",
    ...t.shadows.sm,
  },
  ringCard: { width: 240, alignItems: "center", gap: t.spacing[3] },
  ringCenter: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, alignItems: "center", justifyContent: "center" },
  ringValue: {
    fontSize: t.fontSize["2xl"],
    fontWeight: t.fontWeight.bold,
    color: t.colors.textPrimary,
    letterSpacing: t.letterSpacing.tight,
  },
  riskLabel: { fontSize: t.fontSize.xs, fontWeight: t.fontWeight.bold, letterSpacing: t.letterSpacing.caps },
  riskTrack: { flexDirection: "row", gap: t.spacing[1] },
  riskSeg: { flex: 1, height: 10, borderRadius: t.radii.full },

  /* navigation */
  navStack: { gap: t.spacing[4], width: 380 },
  navPanel: { width: 380, minHeight: 176, justifyContent: "center" },
  centerCol: { alignItems: "center", gap: t.spacing[2] },
  navBar: { width: 380, flexDirection: "row", paddingVertical: t.spacing[3], paddingHorizontal: t.spacing[2] },
  navItem: { flex: 1, alignItems: "center", gap: t.spacing[1] },
  navIconActive: { backgroundColor: t.colors.actionPrimary, ...t.shadows.md },
  navLabel: { fontSize: 11, color: t.colors.textSecondary },
  navLabelActive: { color: t.colors.textPrimary, fontWeight: t.fontWeight.semibold },

  /* login */
  loginCard: { width: 380, gap: t.spacing[5], padding: t.spacing[6] },
  loginHead: { gap: t.spacing[4] },
  field: { gap: 6 },
  fieldLabel: { fontSize: t.fontSize.sm, fontWeight: t.fontWeight.medium, color: t.colors.textSecondary },
  fieldError: { fontSize: t.fontSize.xs, color: t.colors.error },
  phoneRow: { flexDirection: "row", gap: t.spacing[2], alignItems: "stretch" },
  ccSelect: { width: 112 },
  link: { fontSize: t.fontSize.sm, fontWeight: t.fontWeight.medium, color: t.colors.actionPrimary },
  orRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[3] },
  orLine: { flex: 1, height: t.sizes.fieldBorderWidth, backgroundColor: t.colors.border },
  centerText: { textAlign: "center" },

  /* family members */
  stripRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[4] },
  stripCell: { alignItems: "center", gap: 6, width: 60 },
  stripRing: {
    padding: 3,
    // Android: borderRadius > h/2 + borderWidth breaks the background fill.
    borderRadius: 29,
    borderWidth: 2,
    borderColor: t.colors.actionPrimary,
  },
  stripAdd: {
    width: 54,
    height: 54,
    // Android: borderRadius > h/2 + borderWidth breaks the background fill.
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: t.colors.surfaceSunken,
    borderWidth: t.sizes.fieldBorderWidth,
    borderColor: t.colors.border,
  },
  stripScroll: { flex: 1, marginRight: -t.spacing[5] },
  stripContent: { paddingRight: t.spacing[5] },
  stripRingSelected: {
    borderWidth: 3,
    backgroundColor: t.colors.actionPrimarySubtle,
  },
  stripName: { fontSize: 11, color: t.colors.textSecondary, textAlign: "center" },
  stripNameSelected: { color: t.colors.textPrimary, fontWeight: t.fontWeight.semibold },
  starRow: { flexDirection: "row", gap: 3 },
  contactRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[2] },
  onlineDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 10,
    height: 10,
    // Android: borderRadius > h/2 + borderWidth breaks the background fill.
    borderRadius: 5,
    backgroundColor: t.colors.success,
    borderWidth: 2,
  },
  statusDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 14,
    height: 14,
    // Android: borderRadius > h/2 + borderWidth breaks the background fill.
    borderRadius: 7,
    borderWidth: 2,
  },
  bubbleIn: {
    alignSelf: "flex-start",
    maxWidth: "82%",
    backgroundColor: t.colors.surfaceSunken,
    borderRadius: t.radii.lg,
    borderTopLeftRadius: t.radii.sm,
    padding: t.spacing[3],
  },
  bubbleOut: {
    alignSelf: "flex-end",
    maxWidth: "82%",
    backgroundColor: t.colors.actionPrimary,
    borderRadius: t.radii.lg,
    borderTopRightRadius: t.radii.sm,
    padding: t.spacing[3],
  },
  chatInputRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[2] },
  weekStripRow: { flexDirection: "row", gap: t.spacing[2] },
  weekDay: {
    width: 34,
    paddingVertical: t.spacing[2],
    borderRadius: t.radii.md,
    alignItems: "center",
    gap: 4,
  },
  weekDayActive: { backgroundColor: t.colors.actionPrimary, ...t.shadows.sm },
  weekNum: { fontSize: t.fontSize.sm, fontWeight: t.fontWeight.semibold, color: t.colors.textPrimary },

  /* PIN cells */
  pinRowCells: { flexDirection: "row", gap: t.spacing[3] },
  pinCell: {
    width: 52,
    height: 56,
    borderRadius: t.radii.md,
    backgroundColor: t.colors.surface,
    borderWidth: t.sizes.fieldBorderWidth,
    borderColor: t.colors.border,
    alignItems: "center",
    justifyContent: "center",
    ...t.shadows.sm,
  },
  pinDot: {
    width: 12,
    height: 12,
    borderRadius: t.radii.full,
    backgroundColor: t.colors.textPrimary,
  },
  pinHintRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[2] },

  /* popups & alerts */
  popupCard: { width: 320, gap: t.spacing[4] },
  popupIcon: {
    width: 56,
    height: 56,
    borderRadius: t.radii.full,
    alignItems: "center",
    justifyContent: "center",
  },
  variantTag: {
    fontSize: 11,
    fontWeight: t.fontWeight.semibold,
    letterSpacing: t.letterSpacing.caps,
    color: t.colors.textMuted,
    textTransform: "uppercase",
  },
  toastCard: { width: 320, gap: t.spacing[3], paddingBottom: t.spacing[3] },
  toastRow: { flexDirection: "row", alignItems: "center", gap: t.spacing[3] },
  toastIcon: {
    width: 36,
    height: 36,
    borderRadius: t.radii.full,
    alignItems: "center",
    justifyContent: "center",
  },
  toastBar: { height: 3, borderRadius: t.radii.full, alignSelf: "stretch" },
  grabber: {
    width: 40,
    height: 5,
    borderRadius: t.radii.full,
    backgroundColor: t.colors.borderStrong,
    alignSelf: "center",
  },
  sheetActions: { flexDirection: "row", gap: t.spacing[3] },

  /* home variants */
  homeCard: { width: 380, gap: t.spacing[4], padding: t.spacing[5] },
  homeNavRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: t.spacing[3],
    borderTopWidth: t.sizes.fieldBorderWidth,
    borderTopColor: t.colors.borderSubtle,
  },
  homeNavItem: { alignItems: "center", gap: 4 },
  heroRing: {
    width: 150,
    height: 150,
    // Android: borderRadius > h/2 + borderWidth breaks the background fill.
    borderRadius: 75,
    borderWidth: 3,
    borderColor: t.colors.actionPrimary,
    backgroundColor: t.colors.surfaceSunken,
    alignItems: "center",
    justifyContent: "center",
    ...t.shadows.md,
  },
  homePanel: {
    backgroundColor: t.colors.surfaceSunken,
    borderRadius: t.radii.lg,
    padding: t.spacing[4],
    gap: t.spacing[3],
  },
  quickGrid: { flexDirection: "row", flexWrap: "wrap", gap: t.spacing[3] },
  quickTile: {
    width: "47.5%",
    backgroundColor: t.colors.surfaceSunken,
    borderRadius: t.radii.lg,
    padding: t.spacing[3],
    gap: t.spacing[2],
  },

  /* document presentation */
  idCard: { width: 340, backgroundColor: t.colors.actionPrimary, borderColor: "transparent", gap: t.spacing[4] },
  idCardTitle: { fontSize: t.fontSize.lg, fontWeight: t.fontWeight.semibold, color: t.colors.textPrimary },
  idCardMeta: { fontSize: t.fontSize.sm, color: t.colors.textSecondary },
  idCardMetaValue: { fontSize: t.fontSize.md, fontWeight: t.fontWeight.semibold, color: t.colors.textPrimary },
  idNumber: {
    fontFamily: t.fontFamily.mono.semibold,
    fontSize: t.fontSize["2xl"],
    letterSpacing: t.letterSpacing.wide,
    color: t.colors.onActionPrimary,
  },
  kvGrid: { flexDirection: "row", flexWrap: "wrap", gap: t.spacing[3] },
  kvItem: { width: "47%", gap: 2 },

  /* liveness studio */
  liveCard: { width: 380, alignItems: "center", gap: t.spacing[4], paddingVertical: t.spacing[6] },
  liveHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", alignSelf: "stretch" },
  liveStage: { width: 240, height: 240, alignItems: "center", justifyContent: "center" },
  liveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: t.spacing[3],
    paddingVertical: 5,
    borderRadius: t.radii.full,
  },
  liveBadgeDot: { width: 7, height: 7, borderRadius: t.radii.full },
  liveBadgeText: { fontSize: 10, fontWeight: t.fontWeight.bold, letterSpacing: t.letterSpacing.caps },
}));
